[env:ethermesh-1w]
extends = esp32p4_base
board = esp32-p4-evboard
board_level = extra
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = PRIVATE_HW
custom_meshtastic_architecture = esp32
custom_meshtastic_support_level = 3
custom_meshtastic_actively_supported = false
custom_meshtastic_display_name = MeshSmith EtherMesh-1W
custom_meshtastic_tags = MeshSmith
custom_meshtastic_partition_scheme = 16MB
extra_scripts =
  ${esp32p4_base.extra_scripts}
  pre:variants/esp32p4/ethermesh_1w/build.py
build_unflags =
  ${esp32_common.build_unflags}
  ${esp32p4_base.build_unflags}
  -DMESHTASTIC_EXCLUDE_MQTT=1
build_flags =
  ${esp32p4_base.build_flags}
  -I variants/esp32p4/ethermesh_1w
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DMESHTASTIC_EXCLUDE_BLUETOOTH=1
  -DMESHTASTIC_EXCLUDE_AUDIO=1
  -DMESHTASTIC_EXCLUDE_SCREEN=1
  -DMESHTASTIC_EXCLUDE_WEBSERVER=1
build_src_filter =
  ${esp32p4_base.build_src_filter}
  +<serialization/>
  +<../variants/esp32p4/ethermesh_1w>
custom_component_remove = ${esp32_common.custom_component_remove}
custom_sdkconfig =
  ${esp32_common.custom_sdkconfig}
  CONFIG_BT_ENABLED=n
  CONFIG_BT_CONTROLLER_ENABLED=n
  CONFIG_BT_NIMBLE_ENABLED=n
  CONFIG_ESP_HOSTED_ENABLED=n
  CONFIG_ESP_WIFI_REMOTE_ENABLED=n
  CONFIG_ARDUINO_SELECTIVE_BLE=n
  CONFIG_ARDUINO_SELECTIVE_WiFi=n
  CONFIG_ARDUINO_SELECTIVE_Ethernet=y
  CONFIG_ETH_ENABLED=y
  CONFIG_ETH_USE_ESP32_EMAC=y
lib_ignore =
  ${esp32p4_base.lib_ignore}
  ESP32 Codec2
monitor_speed = 115200
