[env:meshsmith-photon-nrf]
extends = nrf52840_base
board = xiao_ble_sense
board_level = extra
board_build.ldscript = src/platform/nrf52/nrf52840_s140_v7.ld
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = PRIVATE_HW
custom_meshtastic_architecture = nrf52840
custom_meshtastic_support_level = 3
custom_meshtastic_actively_supported = false
custom_meshtastic_display_name = MeshSmith Photon NRF
custom_meshtastic_tags = MeshSmith
build_flags =
  ${nrf52840_base.build_flags}
  -I variants/nrf52840/meshsmith_photon_nrf
  -I src/platform/nrf52/softdevice
  -I src/platform/nrf52/softdevice/nrf52
  -DPRIVATE_HW
build_src_filter =
  ${nrf52_base.build_src_filter}
  +<../variants/nrf52840/meshsmith_photon_nrf>
debug_tool = jlink
