[env:meshsmith-photon-c6]
extends = esp32c6_base
board = esp32-c6-devkitm-1
board_level = extra
board_build.flash_mode = dio
board_upload.flash_size = 4MB
custom_meshtastic_hw_model = 255
custom_meshtastic_hw_model_slug = PRIVATE_HW
custom_meshtastic_architecture = esp32-c6
custom_meshtastic_support_level = 3
custom_meshtastic_actively_supported = false
custom_meshtastic_display_name = MeshSmith Photon C6
custom_meshtastic_tags = MeshSmith
extra_scripts =
  ${esp32c6_base.extra_scripts}
  pre:variants/esp32c6/meshsmith_photon_c6/build.py
build_flags =
  ${esp32c6_base.build_flags}
  -I variants/esp32c6/meshsmith_photon_c6
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
  -DMESHTASTIC_EXCLUDE_AUDIO=1
  -DMESHTASTIC_EXCLUDE_SCREEN=1
build_src_filter =
  ${esp32c6_base.build_src_filter}
  +<../variants/esp32c6/meshsmith_photon_c6>
lib_ignore =
  ${esp32c6_base.lib_ignore}
  ESP32 Codec2
monitor_speed = 115200
